/** Every user-facing string lives here, ready for translation. No emojis. */
export const strings = {
  appName: 'Trek',
  tabs: {
    today: 'Today',
    stats: 'Stats',
    goals: 'Goals',
    settings: 'Settings',
  },
  status: {
    done: 'Done',
    partial: 'Partial',
    skipped: 'Skipped',
    vacation: 'Vacation',
    missed: 'Missed',
    pending: 'Pending',
    notDue: 'Not due',
  },
  today: {
    title: 'Today',
    pendingSection: 'To do',
    doneSection: 'Done',
    allDoneTitle: 'All done for today',
    allDoneBody: 'Nice work. See you tomorrow.',
    emptyTitle: 'Create your first goal',
    emptyBody: 'Start with a template or make your own.',
    vacationBanner: 'Vacation mode is on',
    endVacation: 'End vacation now',
    backupBanner: (days: number) => (days === 1 ? 'Last backup 1 day ago' : `Last backup ${days} days ago`),
    backUpNow: 'Back up now',
    snoozeBackup: 'Snooze 3 days',
    timesThisWeek: (done: number, target: number) => `${done} of ${target} this week`,
    selectDay: (label: string) => `Show ${label}`,
    markDone: (goal: string) => `Mark ${goal} done`,
    increment: (goal: string) => `Add one to ${goal}`,
    toggleSlot: (goal: string, time: string) => `Toggle ${goal} at ${time}`,
    undo: 'Undo',
  },
  stats: {
    title: 'Stats',
    allGoals: 'All goals',
    chooseGroup: 'Choose group',
    ranges: { d7: '7D', d30: '30D', d90: '90D', y1: '1Y', all: 'All' },
    rangeLabel: 'Date range',
    modeLabel: 'Partial days',
    weighted: 'Weighted',
    strict: 'Strict',
    completion: 'Completion',
    currentStreak: 'Current streak',
    bestStreak: 'Best streak',
    days: (n: number) => (n === 1 ? '1 day' : `${n} days`),
    heatmap: 'Activity',
    weeklyBars: 'Weekly',
    trend: 'Trend',
    perGoal: 'By goal',
    bestWeekday: 'Best weekday',
    weeklyReview: 'Weekly review',
    monthlyReview: 'Monthly review',
    openReview: (label: string) => `Open ${label}`,
    createGroupTitle: 'Create a group',
    createGroupBody: 'Group goals to compare them here.',
    emptyRequireGroup: 'Create a group with goals to see statistics',
    createGroupAction: 'Create group',
  },
  goalForm: {
    newTitle: 'New goal',
    editTitle: 'Edit goal',
    nameLabel: 'Goal name',
    namePlaceholder: 'What do you want to do?',
    templates: 'Templates',
    templateNames: { water: 'Water', workout: 'Workout', reading: 'Reading', meditation: 'Meditation' },
    useTemplate: (name: string) => `Use ${name} template`,
    sections: {
      schedule: 'Schedule',
      times: 'Times per day',
      tracking: 'Tracking',
      duration: 'Duration',
      reminders: 'Reminders',
      appearance: 'Appearance',
    },
    toggleSection: (name: string) => `Show or hide ${name}`,
    scheduleTypes: {
      daily: 'Every day',
      weekdays: 'Weekdays',
      weekends: 'Weekends',
      customDays: 'Custom days',
      everyNDays: 'Every N days',
      timesPerWeek: 'Times per week',
    },
    scheduleNote: 'Changes apply from today; past stats are kept',
    weekdayToggle: (day: string) => `Toggle ${day}`,
    noTimes: 'Any time',
    trackingSummary: 'Check off',
    durationSummary: 'Open-ended',
    remindersSummary: 'None',
    colorLabel: 'Color',
    chooseColor: (index: number) => `Choose color ${index}`,
    customColor: 'Custom color',
    contrastPass: 'Readable (AA)',
    contrastFail: 'Low contrast',
    iconLabel: 'Icon',
    chooseIcon: (name: string) => `Choose icon ${name}`,
    save: 'Save goal',
  },
  history: {
    title: 'History',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    currentStreak: 'Current streak',
    bestStreak: 'Best streak',
    monthCompletion: 'This month',
    legend: 'Legend',
    dayLabel: (date: string, status: string) => `${date}, ${status}`,
    sheetTitle: (date: string) => `Log for ${date}`,
    value: 'Value',
    decrease: 'Decrease value',
    increaseValue: 'Increase value',
    note: 'Note',
    notePlaceholder: 'Add a note',
    noteCount: (n: number) => `${n}/1000`,
    clear: 'Clear entry',
    save: 'Save',
  },
  review: {
    weekTitle: (week: number) => `Week ${week}`,
    previousPeriod: 'Previous period',
    nextPeriod: 'Next period',
    overall: 'Overall completion',
    changeUp: (pct: number) => `Up ${pct}% vs previous`,
    changeDown: (pct: number) => `Down ${pct}% vs previous`,
    perGoal: 'By goal',
    best: 'Best goal',
    worst: 'Needs attention',
    streaksGained: 'Streaks gained',
    streaksLost: 'Streaks lost',
    bestWeekday: 'Best weekday',
    bestSlot: 'Best time',
    totals: 'Totals',
    insights: 'Insights',
  },
  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    theme: 'Theme',
    accent: 'Accent color',
    weekStart: 'Week starts on',
    timeFormat: 'Time format',
    dayEndsAt: 'My day ends at',
    haptics: 'Haptics',
    reduceMotion: 'Reduce motion',
    vacation: 'Vacation',
    backup: 'Backup and export',
    security: 'Security',
    widget: 'Widget',
    about: 'About',
    exportErrorLog: 'Export error log',
    open: (name: string) => `Open ${name}`,
  },
  lock: {
    title: 'Trek is locked',
    body: 'Unlock to see your goals.',
    unlock: 'Unlock',
  },
  splash: {
    tagline: 'One step a day',
  },
  designPreview: {
    title: 'Design preview',
    devOnly: 'Development only',
    light: 'Light',
    dark: 'Dark',
    modeLabel: 'Color mode',
    screens: {
      splash: 'Splash',
      today: 'Today',
      stats: 'Stats',
      createGoal: 'Create goal',
      history: 'History',
      review: 'Review',
      settings: 'Settings',
      lock: 'Lock',
    },
    openScreen: (name: string) => `Open ${name} preview`,
  },
  navigation: {
    back: 'Back',
    tabBar: 'Tabs',
  },
  devTools: {
    title: 'Developer',
    designPreview: 'Design preview',
    motionCheck: 'Motion check',
    open: (name: string) => `Open ${name}`,
  },
  motionCheck: {
    title: 'Motion check',
    reduceMotionOn: 'Reduce motion is on',
    reduceMotionOff: 'Reduce motion is off',
    replay: 'Replay',
    presets: 'Fade, slide and scale',
    fade: 'Fade in',
    slide: 'Slide up',
    scale: 'Scale in',
    stagger: 'Stagger',
    staggerItem: (n: number) => `Item ${n}`,
    press: 'Press and hold',
    number: 'Counter',
    changeNumber: 'Change number',
    skeleton: 'Skeleton',
    collapse: 'Collapse',
    toggleCollapse: 'Show or hide details',
    details: 'These details fade in while the layout below moves.',
    check: 'Checkmark',
    toggleCheck: 'Toggle checkmark',
    mark: 'Trek mark',
  },
} as const;
