/** Every user-facing string lives here, ready for translation. No emojis. */
import { BACKUP_SNOOZE_DAYS } from '../domain/backupPolicy';
import { NOTE_MAX_LENGTH } from '../domain/limits';

export const strings = {
  appName: 'Trek',
  startup: {
    errorTitle: 'Trek could not start',
    errorBody: 'Restart the app. If this keeps happening, export the error log from Settings.',
  },
  notifications: {
    markDone: 'Mark done',
    snooze: 'Snooze 10 min',
    snoozeBody: 'Reminder',
    goalBody: 'Time to check in',
    genericBody: 'Reminder',
    fallbackGoalTitle: 'Goal reminder',
    weeklyReviewTitle: 'Weekly review',
    weeklyReviewBody: 'Your week is ready to review',
    monthlyReviewTitle: 'Monthly review',
    monthlyReviewBody: 'Your month is ready to review',
    backupTitle: 'Backup',
    backupBody: 'Your last backup is overdue',
    reviewsChannel: 'Reviews',
    backupChannel: 'Backup',
  },
  tabs: {
    today: 'Today',
    stats: 'Stats',
    goals: 'Goals',
    settings: 'Settings',
  },
  status: {
    done: 'Done',
    partial: 'Partial',
    skipped: 'Skipped',
    vacation: 'Vacation',
    missed: 'Missed',
    pending: 'Pending',
    notDue: 'Not due',
  },
  today: {
    title: 'Today',
    pendingSection: 'To do',
    doneSection: 'Done',
    allDoneTitle: 'All done for today',
    allDoneBody: 'Nice work. See you tomorrow.',
    emptyTitle: 'Create your first goal',
    emptyBody: 'Start with a template or make your own.',
    vacationBanner: 'Vacation mode is on',
    endVacation: 'End vacation now',
    backupBanner: (days: number) => (days === 1 ? 'Last backup 1 day ago' : `Last backup ${days} days ago`),
    backUpNow: 'Back up now',
    snoozeBackup: `Snooze ${BACKUP_SNOOZE_DAYS} days`,
    timesThisWeek: (done: number, target: number) => `${done} of ${target} this week`,
    selectDay: (label: string) => `Show ${label}`,
    markDone: (goal: string) => `Mark ${goal} done`,
    increment: (goal: string) => `Add one to ${goal}`,
    toggleSlot: (goal: string, time: string) => `Toggle ${goal} at ${time}`,
    undo: 'Undo',
    nothingDueTitle: 'Nothing due',
    nothingDueBody: 'No goals are scheduled for this day.',
    addMinutes: (goal: string, n: number) => `Add ${n} minutes to ${goal}`,
    enterValue: (goal: string) => `Enter a value for ${goal}`,
    markNotDone: (goal: string) => `Mark ${goal} not done`,
    actionDone: 'Mark done',
    actionSkip: 'Mark skipped',
    actionLog: 'Log details',
    rowLabel: (name: string, status: string, detail: string) => (detail ? `${name}, ${status}, ${detail}` : `${name}, ${status}`),
    progressSlots: (done: number, total: number) => `${done} of ${total} times`,
    progressAmount: (value: number, target: number, unit: string | null) => `${value} of ${target}${unit ? ` ${unit}` : ''}`,
    toastDone: (goal: string) => `${goal} done`,
    toastSkipped: (goal: string) => `${goal} skipped`,
    toastUpdated: (goal: string) => `${goal} updated`,
    toastCleared: (goal: string) => `${goal} cleared`,
    toastMilestone: (goal: string, days: number) => `${goal} done. ${days} day streak`,
    logSheetTitle: (goal: string) => `Log ${goal}`,
    valueSheetTitle: (goal: string) => `Set value for ${goal}`,
    valueLabel: 'Value',
    noteLabel: 'Note',
    doneToggle: 'Done',
    save: 'Save',
    clearEntry: 'Clear entry',
    noteNeedsProgress: 'Add progress to save a note',
    closeSheet: 'Close',
    dateStrip: 'Choose day',
  },
  stats: {
    title: 'Stats',
    allGoals: 'All goals',
    chooseGroup: 'Choose group',
    ranges: { d7: '7D', d30: '30D', d90: '90D', y1: '1Y', all: 'All' },
    rangeLabel: 'Date range',
    modeLabel: 'Partial days',
    weighted: 'Weighted',
    strict: 'Strict',
    completion: 'Completion',
    currentStreak: 'Current streak',
    bestStreak: 'Best streak',
    days: (n: number) => (n === 1 ? '1 day' : `${n} days`),
    weeks: (n: number) => (n === 1 ? '1 week' : `${n} weeks`),
    heatmap: 'Activity',
    weeklyBars: 'Weekly',
    trend: 'Trend',
    perGoal: 'By goal',
    bestWeekday: 'Best weekday',
    weeklyReview: 'Weekly review',
    monthlyReview: 'Monthly review',
    openReview: (label: string) => `Open ${label}`,
    createGroupTitle: 'Create a group',
    createGroupBody: 'Group goals to compare them here.',
    emptyRequireGroup: 'Create a group with goals to see statistics',
    createGroupAction: 'Create group',
    loading: 'Loading statistics',
    completionSummary: (percent: number) => `Completion ${percent} percent`,
    countsSummary: (done: number, partial: number, skipped: number, vacation: number, missed: number) =>
      `${done} done, ${partial} partial, ${skipped} skipped, ${vacation} vacation, ${missed} missed`,
    bestWeekdayNone: 'Not enough data yet',
    reviewsTitle: 'Reviews',
    unitDays: 'days',
    unitWeeks: 'weeks',
    noChartData: 'Not enough data yet',
    legendNone: 'Not scored',
    legendDone: 'Scored (darker is more)',
    legendMissed: 'Missed (crossed)',
    legendVacation: 'Vacation (airplane)',
    heatmapSummary: (days: number, scored: number, full: number, missed: number, vacation = 0) =>
      `${days} days shown, ${scored} scored, ${full} fully complete, ${missed} missed${vacation > 0 ? `, ${vacation} on vacation` : ''}`,
    weeklySummary: (weeks: number, last: number, avg: number) => `${weeks} weeks, latest ${last} percent, average ${avg} percent`,
    trendSummary: (first: number, last: number) => `Seven day average from ${first} percent to ${last} percent`,
    perGoalItem: (name: string, percent: number) => `${name} ${percent} percent`,
  },
  goals: {
    title: 'Goals',
    newGoal: 'New goal',
    emptyTitle: 'Create your first goal',
    emptyBody: 'Start from a template or build your own.',
    paused: 'Paused',
    rowActions: (name: string) => `Actions for ${name}`,
    openGoal: (name: string) => `Open ${name}`,
    dragHandle: (name: string) => `Reorder ${name}. Long press and drag.`,
    sheetTitle: (name: string) => `Actions for ${name}`,
    edit: 'Edit',
    duplicate: 'Duplicate',
    pause: 'Pause',
    resume: 'Resume',
    archive: 'Archive',
    moveUp: 'Move up',
    moveDown: 'Move down',
    close: 'Close',
    confirmArchiveTitle: (name: string) => `Archive ${name}?`,
    confirmArchiveBody: 'It leaves your list. History and stats are kept.',
    confirmArchive: 'Archive goal',
    cancel: 'Cancel',
    history: 'History',
    historyFor: (name: string) => `History for ${name}`,
  },
  vacationMode: {
    title: 'Vacation',
    back: 'Back',
    newVacation: 'New vacation',
    editTitle: 'Edit vacation',
    newTitle: 'New vacation',
    activeSection: 'Active and upcoming',
    pastSection: 'Past',
    emptyTitle: 'No vacations',
    emptyBody: 'Plan time away. Vacation days never break a streak and stay out of your stats.',
    range: (start: string, end: string) => (start === end ? start : `${start} to ${end}`),
    scopeAll: 'All goals',
    scopeSelected: (names: string) => `Selected goals: ${names}`,
    scopeNone: 'Selected goals: none',
    badgeActive: 'Active',
    badgeUpcoming: 'Upcoming',
    badgePast: 'Past',
    edit: (range: string) => `Edit vacation ${range}`,
    endNow: (range: string) => `End vacation ${range} now`,
    endNowLabel: 'End now',
    editLabel: 'Edit',
    deleteLabel: 'Delete',
    deleteAction: (range: string) => `Delete vacation ${range}`,
    confirmDeleteTitle: 'Delete this vacation?',
    confirmDeleteBody: 'Days it covered count as normal days again.',
    confirmDelete: 'Delete vacation',
    cancel: 'Cancel',
    startLabel: 'Start date (YYYY-MM-DD)',
    endLabel: 'End date (YYYY-MM-DD)',
    datePlaceholder: 'YYYY-MM-DD',
    scopeLabel: 'Applies to',
    scopeAllChip: 'All goals',
    scopeSelectedChip: 'Selected goals',
    goalsLabel: 'Goals',
    noGoals: 'Create a goal first.',
    goalRow: (name: string) => `Include ${name}`,
    noteLabel: 'Note (optional)',
    notePlaceholder: 'Where are you going?',
    save: 'Save',
    startInvalid: 'Enter a valid start date.',
    endInvalid: 'Enter a valid end date.',
    startInPast: 'Start must be today or later.',
    endBeforeStart: 'End must not be before start.',
    goalRequired: 'Choose at least one goal.',
    saveFailed: 'Could not save the vacation.',
  },
  groups: {
    title: 'Groups',
    newGroup: 'New group',
    newTitle: 'New group',
    editTitle: 'Edit group',
    emptyTitle: 'Group goals together',
    emptyBody: 'Groups let you see statistics for a set of goals.',
    goalCount: (n: number) => (n === 1 ? '1 goal' : `${n} goals`),
    openGroup: (name: string) => `Edit group ${name}`,
    dragHandle: (name: string) => `Reorder ${name}. Long press and drag.`,
    moveUp: (name: string) => `Move ${name} up`,
    moveDown: (name: string) => `Move ${name} down`,
    nameLabel: 'Group name',
    namePlaceholder: 'Group name',
    colorLabel: 'Color',
    iconLabel: 'Icon',
    goalsLabel: 'Goals in this group',
    noGoals: 'Create a goal first to add it to a group.',
    goalRow: (name: string) => `Include ${name}`,
    back: 'Back',
    save: 'Save group',
    saveFailed: 'Could not save the group',
    nameRequired: 'Enter a group name',
    delete: 'Delete group',
    confirmDeleteTitle: (name: string) => `Delete ${name}?`,
    confirmDeleteBody: 'Its goals are kept. Only the group is removed.',
    confirmDelete: 'Delete group',
    cancel: 'Cancel',
  },
  goalForm: {
    newTitle: 'New goal',
    editTitle: 'Edit goal',
    nameLabel: 'Goal name',
    namePlaceholder: 'What do you want to do?',
    templates: 'Templates',
    templateUnits: { glasses: 'glasses', minutes: 'min' },
    templateNames: { water: 'Water', workout: 'Workout', reading: 'Reading', meditation: 'Meditation' },
    useTemplate: (name: string) => `Use ${name} template`,
    sections: {
      schedule: 'Schedule',
      times: 'Times per day',
      tracking: 'Tracking',
      duration: 'Duration',
      reminders: 'Reminders',
      appearance: 'Appearance',
    },
    toggleSection: (name: string) => `Show or hide ${name}`,
    scheduleTypes: {
      daily: 'Every day',
      weekdays: 'Weekdays',
      weekends: 'Weekends',
      customDays: 'Custom days',
      everyNDays: 'Every N days',
      timesPerWeek: 'Times per week',
    },
    scheduleNote: 'Changes apply from today; past stats are kept',
    weekdayToggle: (day: string) => `Toggle ${day}`,
    weekdaysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    scheduleSummary: {
      customDays: (days: string) => days,
      everyNDays: (n: number) => (n === 1 ? 'Every day' : `Every ${n} days`),
      timesPerWeek: (n: number) => `${n} times per week`,
    },
    everyNLabel: 'Days between',
    timesPerWeekLabel: 'Times per week',
    daysRequired: 'Pick at least one day',
    noTimes: 'Any time',
    timesSummary: (n: number) => (n === 1 ? '1 time' : `${n} times`),
    addTime: 'Add time',
    removeTime: (time: string) => `Remove ${time}`,
    sameOnAllDays: 'Same on all days',
    slotsFor: (day: string) => `Times for ${day}`,
    timeLabel: 'Time',
    slotLabelPlaceholder: 'Label (optional)',
    slotLabelField: 'Time label',
    earlierTime: 'Earlier by 15 minutes',
    laterTime: 'Later by 15 minutes',
    trackingTypes: { check: 'Check off', count: 'Count', duration: 'Duration', value: 'Value' },
    trackingSummary: 'Check off',
    trackingSummaryWith: (type: string, target: string, unit: string) => `${type} · ${target}${unit ? ` ${unit}` : ''}`,
    targetLabel: 'Target (at least)',
    unitLabel: 'Unit',
    unitPlaceholder: 'glasses, min, pages',
    durationSummary: 'Open-ended',
    durationModes: { open: 'Open-ended', endDate: 'End date', targetDays: 'Target days' },
    durationEndSummary: (date: string) => `Until ${date}`,
    durationDaysSummary: (n: number) => `${n} days`,
    datePlaceholder: 'YYYY-MM-DD',
    endDateLabel: 'End date (YYYY-MM-DD)',
    targetDaysLabel: 'Number of days',
    remindersSummary: 'None',
    remindersSummaryOn: (days: number, time: string) => `${days === 7 ? 'Every day' : `${days} days`} at ${time}`,
    remindersSummarySlots: (days: number) => `${days === 7 ? 'Every day' : `${days} days`}, at each time`,
    remindMe: 'Remind me',
    reminderDays: 'Reminder days',
    reminderTime: 'Reminder time',
    followsSlots: 'Reminders follow each time on the days that have times',
    minutesBefore: 'Minutes before',
    appearanceSummary: 'Color and icon',
    colorLabel: 'Color',
    chooseColor: (index: number) => `Choose color ${index}`,
    customColor: 'Custom color',
    customColorHex: 'Custom color hex',
    hue: 'Hue',
    lightness: 'Lightness',
    contrastPass: 'Readable (AA)',
    contrastFail: 'Low contrast',
    iconLabel: 'Icon',
    chooseIcon: (name: string) => `Choose icon ${name}`,
    increase: (name: string) => `Increase ${name}`,
    decrease: (name: string) => `Decrease ${name}`,
    errors: {
      nameRequired: 'Enter a goal name',
      targetInvalid: 'Target must be greater than 0',
      timeInvalid: 'Use a time like 07:30',
      dateInvalid: 'Use a date like 2026-12-31',
      daysInvalid: 'Enter a whole number of 1 or more',
      colorInvalid: 'Use a color like #2E7D5B',
      saveFailed: 'Could not save the goal',
    },
    save: 'Save goal',
    saveEdit: 'Save changes',
    back: 'Back',
  },
  history: {
    title: 'History',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    currentStreak: 'Current streak',
    bestStreak: 'Best streak',
    monthCompletion: 'This month',
    legend: 'Legend',
    dayLabel: (date: string, status: string) => `${date}, ${status}`,
    sheetTitle: (date: string) => `Log for ${date}`,
    value: 'Value',
    decrease: 'Decrease value',
    increaseValue: 'Increase value',
    note: 'Note',
    notePlaceholder: 'Add a note',
    noteCount: (n: number) => `${n}/${NOTE_MAX_LENGTH}`,
    clear: 'Clear entry',
    save: 'Save',
    close: 'Close sheet',
    back: 'Back',
    openFor: (name: string) => `History for ${name}`,
    screenTitle: (name: string) => `${name} history`,
    notFound: 'This goal could not be found.',
    readOnly: 'read-only',
    dayDetail: (status: string, badge: string | null, readOnly: boolean) =>
      [status, badge, readOnly ? 'read-only' : null].filter(Boolean).join(', '),
    quota: (done: number, target: number) => `${done}/${target}`,
    quotaLabel: (done: number, target: number) => `${done} of ${target} days this week`,
    statusLabel: 'Status',
    slotsLabel: 'Times',
    futureNote: 'Future days cannot be edited.',
    streakDays: (n: number) => (n === 1 ? '1 day' : `${n} days`),
    streakWeeks: (n: number) => (n === 1 ? '1 week' : `${n} weeks`),
    percentNone: 'None yet',
    monthSwipeHint: 'Swipe to change month',
  },
  review: {
    weekTitle: (week: number) => `Week ${week}`,
    previousPeriod: 'Previous period',
    nextPeriod: 'Next period',
    overall: 'Overall completion',
    changeUp: (pts: number) => `+${pts} pts`,
    changeDown: (pts: number) => `\u2212${pts} pts`,
    changeUpLabel: (pts: number) => `Up ${pts} points versus previous period`,
    changeDownLabel: (pts: number) => `Down ${pts} points versus previous period`,
    changeFlatLabel: 'No change',
    noPrevious: 'No previous data',
    noData: 'No data yet',
    overallLabel: (pct: number) => `Overall completion ${pct} percent`,
    loading: 'Loading review',
    notFoundTitle: 'Review not found',
    notFoundBody: 'This review link is not valid.',
    backToStats: 'Back to Stats',
    emptyTitle: 'No goals to review',
    emptyBody: 'Create a goal and log a few days to see a review.',
    createGoal: 'Create goal',
    back: 'Back',
    goalPercent: (name: string, pct: number) => `${name} ${pct} percent`,
    noChartData: 'Not enough data yet',
    streakChange: (name: string, before: number, after: number) => `${name}: ${before} to ${after}`,
    noStreakChange: 'None this period',
    noValue: 'Not enough data',
    slotCount: (label: string, count: number) => `${label} (${count})`,
    buckets: { morning: 'Morning', afternoon: 'Afternoon', evening: 'Evening', night: 'Night' },
    goalValue: (name: string, pct: number) => `${name} ${pct}%`,
    totalsLine: (done: number, skipped: number, vacation: number) => {
      const d = done === 1 ? 'day' : 'days';
      const s = skipped === 1 ? 'day' : 'days';
      const v = vacation === 1 ? 'day' : 'days';
      return `Done ${done} ${d} \u00b7 Skipped ${skipped} ${s} \u00b7 Vacation ${vacation} ${v}`;
    },
    totalsSummary: (done: number, skipped: number, vacation: number) => `Done ${done}, skipped ${skipped}, vacation ${vacation}`,
    perGoal: 'By goal',
    best: 'Best goal',
    worst: 'Needs attention',
    streaksGained: 'Streaks gained',
    streaksLost: 'Streaks lost',
    bestWeekday: 'Best weekday',
    bestSlot: 'Best time',
    totals: 'Totals',
    insights: 'Insights',
  },
  backupScreen: {
    title: 'Backup and export',
    exportTitle: 'Export',
    exportHelp: 'Share a copy of your data. Excel is the default; JSON is lossless; CSV is one file per table.',
    exportXlsx: 'Export Excel',
    exportJson: 'Export JSON',
    exportCsv: 'Export CSV zip',
    exportDone: 'Export ready',
    exportFailed: 'Export failed. Try again.',
    reminderTitle: 'Backup reminder',
    reminderOptions: { off: 'Off', weekly: 'Weekly', biweekly: 'Every 2 weeks', monthly: 'Monthly' },
    formatTitle: 'Reminder backup format',
    formatOptions: { xlsx: 'Excel', json: 'JSON', both: 'Both' },
    autoTitle: 'Automatic backup',
    autoLabel: 'Back up automatically',
    autoHelp: 'Writes a JSON backup on the first open each day and keeps the newest 7.',
    chooseFolder: 'Choose backup folder',
    folderSet: 'Backups are also copied to your chosen folder.',
    folderRevoked: 'Access to the backup folder was lost. Choose the folder again to keep copying backups there.',
    restoreTitle: 'Restore from auto-backup',
    preImportPrefix: (label: string) => `Before import, ${label}`,
    restoreEmpty: 'No automatic backups yet',
    restoreItem: (label: string, kb: string) => `${label} (${kb} KB)`,
    restoreItemLabel: (label: string) => `Restore backup from ${label}`,
    importTitle: 'Import',
    importHelp: 'Import an Excel, JSON or CSV zip file exported by Trek.',
    importButton: 'Import a file',
    importUnreadable: (reason: string) => `This file cannot be imported. ${reason}`,
    previewTitle: 'Import preview',
    previewCount: (sheet: string, valid: number, total: number) => `${sheet}: ${valid} of ${total} rows`,
    previewErrors: (n: number) => `${n} invalid rows`,
    previewError: (sheet: string, row: number, message: string) => `${sheet}, row ${row}: ${message}`,
    previewMoreErrors: (n: number) => `And ${n} more`,
    skipInvalid: (n: number) => `Skip ${n} invalid rows`,
    skipInvalidLabel: 'Confirm skipping invalid rows',
    mode: 'Import mode',
    replace: 'Replace',
    merge: 'Merge',
    replaceHelp: 'Replace deletes current data first. A backup is saved before importing.',
    mergeHelp: 'Merge keeps newer changes by id. A backup is saved before importing.',
    runImport: 'Import',
    cancel: 'Cancel',
    importDone: 'Import complete',
    importFailed: 'Import failed. Your data was not changed.',
  },
  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    theme: 'Theme',
    accent: 'Accent color',
    weekStart: 'Week starts on',
    timeFormat: 'Time format',
    dayEndsAt: 'My day ends at',
    haptics: 'Haptics',
    reduceMotion: 'Reduce motion',
    appearanceScreen: {
      themeOptions: { system: 'System', light: 'Light', dark: 'Dark' },
      weekStartOptions: { sunday: 'Sunday', monday: 'Monday', saturday: 'Saturday' },
      timeFormatOptions: { h12: '12-hour', h24: '24-hour' },
      reduceMotionOptions: { system: 'System', on: 'On', off: 'Off' },
      midnight: 'Midnight',
      dayEndsHelp: 'Check-ins before this time count for the previous day.',
      hapticsLabel: 'Haptic feedback',
      accentPreview: 'Accent preview',
      previewLight: 'Light',
      previewDark: 'Dark',
      previewFor: (mode: string) => `${mode} accent preview`,
      dayEndsOption: (label: string) => `Day ends at ${label}`,
    },
    vacation: 'Vacation',
    backup: 'Backup and export',
    security: 'Security',
    widget: 'Widget',
    about: 'About',
    exportErrorLog: 'Export error log',
    notifications: {
      title: 'Notifications',
      on: 'On',
      off: 'Off',
      blocked: 'Blocked in system settings',
      notAsked: 'Not enabled yet',
      enable: 'Turn on',
      openSettings: 'Open settings',
    },
    open: (name: string) => `Open ${name}`,
  },
  lock: {
    title: 'Trek is locked',
    body: 'Unlock to see your goals.',
    unlock: 'Unlock',
    prompt: 'Unlock Trek',
    cancelLabel: 'Cancel',
    failed: 'That did not work. Try again.',
    usePasscode: 'Too many tries. Use your device passcode.',
    privacyOverlay: 'Trek privacy screen',
  },
  security: {
    title: 'Security',
    appLock: 'App lock',
    appLockLabel: 'Require unlock to open Trek',
    appLockHelp: 'Uses your biometrics, with your device passcode as a fallback. Trek never stores a PIN.',
    notEnrolled: 'Set up a screen lock or biometrics in your device settings first. App lock stays off until then.',
    authFailed: 'Could not confirm it is you, so app lock stays off.',
    timeout: 'Lock after',
    timeoutHelp: 'How long Trek can stay in the background before it locks.',
    timeoutOptions: { immediate: 'Immediately', '1m': '1 minute', '5m': '5 minutes', '15m': '15 minutes' },
    hideInSwitcher: 'Hide in app switcher',
    hideInSwitcherLabel: 'Blur Trek in the app switcher',
    hideInSwitcherHelp: 'Shows a blurred screen while Trek is not in front.',
    enablePrompt: 'Confirm to turn on app lock',
  },
  splash: {
    tagline: 'One step a day',
  },
  designPreview: {
    title: 'Design preview',
    devOnly: 'Development only',
    light: 'Light',
    dark: 'Dark',
    modeLabel: 'Color mode',
    screens: {
      splash: 'Splash',
      today: 'Today',
      stats: 'Stats',
      createGoal: 'Create goal',
      history: 'History',
      review: 'Review',
      settings: 'Settings',
      lock: 'Lock',
    },
    openScreen: (name: string) => `Open ${name} preview`,
  },
  navigation: {
    back: 'Back',
    tabBar: 'Tabs',
  },
  devTools: {
    title: 'Developer',
    designPreview: 'Design preview',
    motionCheck: 'Motion check',
    seed: 'Seed demo data',
    open: (name: string) => `Open ${name}`,
  },
  insights: {
    templates: {
      overallImproved: 'Overall completion improved {percent}% vs last {period}',
      overallDeclined: 'Overall completion dropped {percent}% vs last {period}',
      goalImproved: '{goal} improved {percent}% vs last {period}',
      goalDeclined: '{goal} dropped {percent}% vs last {period}',
      streakGained: '{goal} streak grew by {days} days',
      mostSkippedWeekday: 'You skip most on {weekday}',
      perfectPeriod: 'A perfect {period}: every due day done',
      mostConsistentGoal: '{goal} was your most consistent goal at {percent}%',
      totalDone: 'Days done this {period}: {count}',
      dueDays: 'Due days this {period}: {count}',
    },
    weekdays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    periods: { week: 'week', month: 'month' },
  },
  motionCheck: {
    title: 'Motion check',
    reduceMotionOn: 'Reduce motion is on',
    reduceMotionOff: 'Reduce motion is off',
    replay: 'Replay',
    presets: 'Fade, slide and scale',
    fade: 'Fade in',
    slide: 'Slide up',
    scale: 'Scale in',
    stagger: 'Stagger',
    staggerItem: (n: number) => `Item ${n}`,
    press: 'Press and hold',
    number: 'Counter',
    changeNumber: 'Change number',
    skeleton: 'Skeleton',
    collapse: 'Collapse',
    toggleCollapse: 'Show or hide details',
    details: 'These details fade in while the layout below moves.',
    check: 'Checkmark',
    toggleCheck: 'Toggle checkmark',
    mark: 'Trek mark',
  },
} as const;
