/** Every user-facing string lives here, ready for translation. No emojis. */
export const strings = {
  appName: 'Trek',
  startup: {
    errorTitle: 'Trek could not start',
    errorBody: 'Restart the app. If this keeps happening, export the error log from Settings.',
  },
  tabs: {
    today: 'Today',
    stats: 'Stats',
    goals: 'Goals',
    settings: 'Settings',
  },
  status: {
    done: 'Done',
    partial: 'Partial',
    skipped: 'Skipped',
    vacation: 'Vacation',
    missed: 'Missed',
    pending: 'Pending',
    notDue: 'Not due',
  },
  today: {
    title: 'Today',
    pendingSection: 'To do',
    doneSection: 'Done',
    allDoneTitle: 'All done for today',
    allDoneBody: 'Nice work. See you tomorrow.',
    emptyTitle: 'Create your first goal',
    emptyBody: 'Start with a template or make your own.',
    vacationBanner: 'Vacation mode is on',
    endVacation: 'End vacation now',
    backupBanner: (days: number) => (days === 1 ? 'Last backup 1 day ago' : `Last backup ${days} days ago`),
    backUpNow: 'Back up now',
    snoozeBackup: 'Snooze 3 days',
    timesThisWeek: (done: number, target: number) => `${done} of ${target} this week`,
    selectDay: (label: string) => `Show ${label}`,
    markDone: (goal: string) => `Mark ${goal} done`,
    increment: (goal: string) => `Add one to ${goal}`,
    toggleSlot: (goal: string, time: string) => `Toggle ${goal} at ${time}`,
    undo: 'Undo',
  },
  stats: {
    title: 'Stats',
    allGoals: 'All goals',
    chooseGroup: 'Choose group',
    ranges: { d7: '7D', d30: '30D', d90: '90D', y1: '1Y', all: 'All' },
    rangeLabel: 'Date range',
    modeLabel: 'Partial days',
    weighted: 'Weighted',
    strict: 'Strict',
    completion: 'Completion',
    currentStreak: 'Current streak',
    bestStreak: 'Best streak',
    days: (n: number) => (n === 1 ? '1 day' : `${n} days`),
    heatmap: 'Activity',
    weeklyBars: 'Weekly',
    trend: 'Trend',
    perGoal: 'By goal',
    bestWeekday: 'Best weekday',
    weeklyReview: 'Weekly review',
    monthlyReview: 'Monthly review',
    openReview: (label: string) => `Open ${label}`,
    createGroupTitle: 'Create a group',
    createGroupBody: 'Group goals to compare them here.',
    emptyRequireGroup: 'Create a group with goals to see statistics',
    createGroupAction: 'Create group',
  },
  goalForm: {
    newTitle: 'New goal',
    editTitle: 'Edit goal',
    nameLabel: 'Goal name',
    namePlaceholder: 'What do you want to do?',
    templates: 'Templates',
    templateUnits: { glasses: 'glasses', minutes: 'min' },
    templateNames: { water: 'Water', workout: 'Workout', reading: 'Reading', meditation: 'Meditation' },
    useTemplate: (name: string) => `Use ${name} template`,
    sections: {
      schedule: 'Schedule',
      times: 'Times per day',
      tracking: 'Tracking',
      duration: 'Duration',
      reminders: 'Reminders',
      appearance: 'Appearance',
    },
    toggleSection: (name: string) => `Show or hide ${name}`,
    scheduleTypes: {
      daily: 'Every day',
      weekdays: 'Weekdays',
      weekends: 'Weekends',
      customDays: 'Custom days',
      everyNDays: 'Every N days',
      timesPerWeek: 'Times per week',
    },
    scheduleNote: 'Changes apply from today; past stats are kept',
    weekdayToggle: (day: string) => `Toggle ${day}`,
    weekdaysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    scheduleSummary: {
      customDays: (days: string) => days,
      everyNDays: (n: number) => (n === 1 ? 'Every day' : `Every ${n} days`),
      timesPerWeek: (n: number) => `${n} times per week`,
    },
    everyNLabel: 'Days between',
    timesPerWeekLabel: 'Times per week',
    daysRequired: 'Pick at least one day',
    noTimes: 'Any time',
    timesSummary: (n: number) => (n === 1 ? '1 time' : `${n} times`),
    addTime: 'Add time',
    removeTime: (time: string) => `Remove ${time}`,
    sameOnAllDays: 'Same on all days',
    slotsFor: (day: string) => `Times for ${day}`,
    timeLabel: 'Time',
    slotLabelPlaceholder: 'Label (optional)',
    slotLabelField: 'Time label',
    earlierTime: 'Earlier by 15 minutes',
    laterTime: 'Later by 15 minutes',
    trackingTypes: { check: 'Check off', count: 'Count', duration: 'Duration', value: 'Value' },
    trackingSummary: 'Check off',
    trackingSummaryWith: (type: string, target: string, unit: string) => `${type} · ${target}${unit ? ` ${unit}` : ''}`,
    targetLabel: 'Target (at least)',
    unitLabel: 'Unit',
    unitPlaceholder: 'glasses, min, pages',
    durationSummary: 'Open-ended',
    durationModes: { open: 'Open-ended', endDate: 'End date', targetDays: 'Target days' },
    durationEndSummary: (date: string) => `Until ${date}`,
    durationDaysSummary: (n: number) => `${n} days`,
    datePlaceholder: 'YYYY-MM-DD',
    endDateLabel: 'End date (YYYY-MM-DD)',
    targetDaysLabel: 'Number of days',
    remindersSummary: 'None',
    remindersSummaryOn: (days: number, time: string) => `${days === 7 ? 'Every day' : `${days} days`} at ${time}`,
    remindersSummarySlots: (days: number) => `${days === 7 ? 'Every day' : `${days} days`}, at each time`,
    remindMe: 'Remind me',
    reminderDays: 'Reminder days',
    reminderTime: 'Reminder time',
    followsSlots: 'Reminders follow each time on the days that have times',
    minutesBefore: 'Minutes before',
    appearanceSummary: 'Color and icon',
    colorLabel: 'Color',
    chooseColor: (index: number) => `Choose color ${index}`,
    customColor: 'Custom color',
    customColorHex: 'Custom color hex',
    hue: 'Hue',
    lightness: 'Lightness',
    contrastPass: 'Readable (AA)',
    contrastFail: 'Low contrast',
    iconLabel: 'Icon',
    chooseIcon: (name: string) => `Choose icon ${name}`,
    increase: (name: string) => `Increase ${name}`,
    decrease: (name: string) => `Decrease ${name}`,
    errors: {
      nameRequired: 'Enter a goal name',
      targetInvalid: 'Target must be greater than 0',
      timeInvalid: 'Use a time like 07:30',
      dateInvalid: 'Use a date like 2026-12-31',
      daysInvalid: 'Enter a whole number of 1 or more',
      colorInvalid: 'Use a color like #2E7D5B',
      saveFailed: 'Could not save the goal',
    },
    save: 'Save goal',
    saveEdit: 'Save changes',
    back: 'Back',
  },
  history: {
    title: 'History',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    currentStreak: 'Current streak',
    bestStreak: 'Best streak',
    monthCompletion: 'This month',
    legend: 'Legend',
    dayLabel: (date: string, status: string) => `${date}, ${status}`,
    sheetTitle: (date: string) => `Log for ${date}`,
    value: 'Value',
    decrease: 'Decrease value',
    increaseValue: 'Increase value',
    note: 'Note',
    notePlaceholder: 'Add a note',
    noteCount: (n: number) => `${n}/1000`,
    clear: 'Clear entry',
    save: 'Save',
  },
  review: {
    weekTitle: (week: number) => `Week ${week}`,
    previousPeriod: 'Previous period',
    nextPeriod: 'Next period',
    overall: 'Overall completion',
    changeUp: (pct: number) => `Up ${pct}% vs previous`,
    changeDown: (pct: number) => `Down ${pct}% vs previous`,
    perGoal: 'By goal',
    best: 'Best goal',
    worst: 'Needs attention',
    streaksGained: 'Streaks gained',
    streaksLost: 'Streaks lost',
    bestWeekday: 'Best weekday',
    bestSlot: 'Best time',
    totals: 'Totals',
    insights: 'Insights',
  },
  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    theme: 'Theme',
    accent: 'Accent color',
    weekStart: 'Week starts on',
    timeFormat: 'Time format',
    dayEndsAt: 'My day ends at',
    haptics: 'Haptics',
    reduceMotion: 'Reduce motion',
    vacation: 'Vacation',
    backup: 'Backup and export',
    security: 'Security',
    widget: 'Widget',
    about: 'About',
    exportErrorLog: 'Export error log',
    open: (name: string) => `Open ${name}`,
  },
  lock: {
    title: 'Trek is locked',
    body: 'Unlock to see your goals.',
    unlock: 'Unlock',
  },
  splash: {
    tagline: 'One step a day',
  },
  designPreview: {
    title: 'Design preview',
    devOnly: 'Development only',
    light: 'Light',
    dark: 'Dark',
    modeLabel: 'Color mode',
    screens: {
      splash: 'Splash',
      today: 'Today',
      stats: 'Stats',
      createGoal: 'Create goal',
      history: 'History',
      review: 'Review',
      settings: 'Settings',
      lock: 'Lock',
    },
    openScreen: (name: string) => `Open ${name} preview`,
  },
  navigation: {
    back: 'Back',
    tabBar: 'Tabs',
  },
  devTools: {
    title: 'Developer',
    designPreview: 'Design preview',
    motionCheck: 'Motion check',
    seed: 'Seed demo data',
    open: (name: string) => `Open ${name}`,
  },
  insights: {
    templates: {
      overallImproved: 'Overall completion improved {percent}% vs last {period}',
      overallDeclined: 'Overall completion dropped {percent}% vs last {period}',
      goalImproved: '{goal} improved {percent}% vs last {period}',
      goalDeclined: '{goal} dropped {percent}% vs last {period}',
      streakGained: '{goal} streak grew by {days} days',
      mostSkippedWeekday: 'You skip most on {weekday}',
      perfectPeriod: 'A perfect {period}: every due day done',
    },
    weekdays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    periods: { week: 'week', month: 'month' },
  },
  motionCheck: {
    title: 'Motion check',
    reduceMotionOn: 'Reduce motion is on',
    reduceMotionOff: 'Reduce motion is off',
    replay: 'Replay',
    presets: 'Fade, slide and scale',
    fade: 'Fade in',
    slide: 'Slide up',
    scale: 'Scale in',
    stagger: 'Stagger',
    staggerItem: (n: number) => `Item ${n}`,
    press: 'Press and hold',
    number: 'Counter',
    changeNumber: 'Change number',
    skeleton: 'Skeleton',
    collapse: 'Collapse',
    toggleCollapse: 'Show or hide details',
    details: 'These details fade in while the layout below moves.',
    check: 'Checkmark',
    toggleCheck: 'Toggle checkmark',
    mark: 'Trek mark',
  },
} as const;
